# Generated by Django 5.0.7 on 2024-08-08 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journeyapp', '0003_triplog_like_count_follow_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='post_id',
            new_name='Log_id',
        ),
    ]
