# Generated by Django 5.0.7 on 2024-08-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeyapp', '0004_rename_post_id_likes_log_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='folllowings_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='followers_no',
            field=models.IntegerField(default=0),
        ),
    ]
