# Generated by Django 5.0.7 on 2024-08-11 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journeyapp', '0008_comment_created_at_comment_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
    ]
